### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by VenelALEX** [VenelALEX/BetterTobaccoMod#1]
### Add Items (Model, Textures, Lang, Functionality)
- [x] Add Tobacco Seeds
- [x] Add Dried Tobacco
- [x] Add Cigarettes
- [ ] Add *Suprise* Item
- [ ] Add Hookah Tobacco

### Add Blocks (Model, Textures, Lang, Functionality)
- [ ] Add Hookah

### Add Concepts for:
- [ ] Hookah
- [ ] Biomes
- [ ] Custom Armor
- [ ] Custom Tools & Weapons
- [ ] Custom Mobs
